"""Send the biweekly digest via Gmail using an App Password."""

import os
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText


def send_digest(subject: str, html_body: str, plain_body: str) -> None:
    """
    Send an email via Gmail SMTP.

    Required environment variables:
      GMAIL_USER         — your Gmail address (e.g. you@gmail.com)
      GMAIL_APP_PASSWORD — 16-char App Password (not your account password)
      RECIPIENT_EMAIL    — destination address
    """
    sender = os.environ["GMAIL_USER"]
    password = os.environ["GMAIL_APP_PASSWORD"]
    recipient = os.environ["RECIPIENT_EMAIL"]

    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"] = f"Chicago Education Digest <{sender}>"
    msg["To"] = recipient

    msg.attach(MIMEText(plain_body, "plain"))
    msg.attach(MIMEText(html_body, "html"))

    with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
        server.login(sender, password)
        server.sendmail(sender, recipient, msg.as_string())

    print(f"Email sent to {recipient}")


# ── HTML / plain-text rendering ───────────────────────────────────────────────

def render_html(
    date_range: str,
    sections: list[dict],  # [{"topic": str, "summary": str, "articles": [dict]}]
) -> str:
    topic_blocks = ""
    for section in sections:
        if not section["articles"]:
            continue
        article_rows = "\n".join(
            f'<li><a href="{a["url"]}">{a["title"]}</a> '
            f'<span style="color:#666;font-size:0.85em">— {a["source"]}, {a["published_str"]}</span></li>'
            for a in section["articles"]
        )
        summary_html = section["summary"].replace("\n\n", "</p><p>").replace("\n", " ")
        topic_blocks += f"""
        <div style="margin-bottom:2em;padding-bottom:1.5em;border-bottom:1px solid #e0e0e0">
          <h2 style="color:#1a3a5c;font-size:1.1em;margin-bottom:0.5em">{section["topic"]}</h2>
          <div style="color:#333;line-height:1.6"><p>{summary_html}</p></div>
          <h3 style="font-size:0.9em;color:#555;margin:1em 0 0.4em">Source Articles</h3>
          <ul style="padding-left:1.2em;margin:0;color:#333;line-height:1.8">
            {article_rows}
          </ul>
        </div>
        """

    return f"""<!DOCTYPE html>
<html>
<head><meta charset="utf-8"></head>
<body style="font-family:Georgia,serif;max-width:680px;margin:0 auto;padding:24px;color:#222">
  <div style="background:#1a3a5c;color:#fff;padding:16px 24px;border-radius:4px 4px 0 0">
    <h1 style="margin:0;font-size:1.3em">Chicago Education Digest</h1>
    <p style="margin:4px 0 0;font-size:0.85em;opacity:0.85">{date_range}</p>
  </div>
  <div style="background:#f9f9f9;padding:4px 24px 8px;font-size:0.8em;color:#555;border:1px solid #ddd;border-top:none">
    Covering: K-12 Education &amp; Schools · Board of Education &amp; Governance
  </div>
  <div style="padding:16px 0">
    {topic_blocks}
  </div>
  <p style="font-size:0.75em;color:#888;margin-top:2em;border-top:1px solid #eee;padding-top:1em">
    Auto-generated by chicago-education digest · Articles sourced from Chalkbeat Chicago,
    Chicago Tribune, Crain's Chicago Business, CPS, and ISBE.
  </p>
</body>
</html>"""


def render_plain(
    date_range: str,
    sections: list[dict],
) -> str:
    lines = [
        "CHICAGO EDUCATION DIGEST",
        date_range,
        "=" * 60,
        "",
    ]
    for section in sections:
        if not section["articles"]:
            continue
        lines += [
            section["topic"].upper(),
            "-" * len(section["topic"]),
            "",
            section["summary"],
            "",
            "Articles:",
        ]
        for a in section["articles"]:
            lines.append(f"  • {a['title']} ({a['source']}, {a['published_str']})")
            lines.append(f"    {a['url']}")
        lines += ["", ""]
    return "\n".join(lines)
